# Exercise 2.8
# Add Nginx to example to work as a reverse proxy in front of the example app frontend and backend. According to Wikipedia
# A reverse proxy is a type of proxy server that retrieves resources on behalf of a client from one or more servers. These resources are then returned to the client, appearing as if they originated from the reverse proxy server itself.
# Backend, frontend, redis, a database and nginx
# So in our case, the reverse proxy will be the single point of entry to our application, and the final goal will be to set both the React frontend and the Express backend behind the reverse proxy.
# The idea is that browser makes all requests to http://localhost. If the request has a url prefix http://localhost/api, Nginx should forward the request to the backend container. All the other requests are directed the frontend container.
# So, at the end you should see that the frontend is accessible simply by going to http://localhost. All buttons, except the one labelled Exercise 2.8 may have stopped working, do not worry about them, we shall fix that later.
# The following file should be set to /etc/nginx/nginx.conf inside the nginx container. You can use a file bind mount where the contents of the file is the following:
# events { worker_connections 1024; }
# http {
#   server {
#     listen 80;
#     location / {
#       proxy_pass _frontend-connection-url_;
#     }
#     # configure here where requests to http://localhost/api/...
#     # are forwarded
#     location /api/ {
#       proxy_set_header Host $host;
#       proxy_pass _backend-connection-url_;
#     }
#   }
# }
# Nginx, backend and frontend should be connected in the same network. See the image above for how the services are connected. You find Nginx-documentation helpful, but remember, the configuration you need is pretty straight forward, if you end up doing complex things, you are most likely doing something wrong.
# If and when your app "does not work", remember to have a look in log, it can be pretty helpful in pinpointing errors:
# 2_7-proxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
# 2_7-proxy-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
# 2_7-proxy-1  | 2023/03/05 09:24:51 [emerg] 1#1: invalid URL prefix in /etc/nginx/nginx.conf:8
# 2_7-proxy-1 exited with code 1
# Submit the docker-compose.yml

version: '3.8'

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - example-backend
      - example-frontend

  example-backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - FRONT_URL=http://localhost
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DATABASE=backend
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  example-frontend:
    image: example-frontend
    ports:
      - 5000:5000
    environment:
      - API_URL=http://example-backend:8080

  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=backend

    volumes:
      - ./database:/var/lib/postgresql/data
