# Mandatory Exercise 2.3
# As we saw previously, starting an application with two programs was not trivial and the commands got a bit long.
# In the previous part we created Dockerfiles for both frontend and backend of the example application. Next, simplify the usage into one docker-compose.yml.
# Configure the backend and frontend from part 1 to work in Docker Compose.
# Submit the docker-compose.yml

version: '3.8'

services:
  example-backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - FRONT_URL=http://localhost:5000

  example-frontend:
    image: example-frontend
    ports:
      - 5000:5000
    environment:
      - API_URL=http://localhost:8080
