# Exercise 2.9
# Most of the buttons may have stopped working in the example application. Make sure that every button for exercises works.
# Remember to take a peek into the browsers developer consoles again like we did back part 1, remember also this and this.
# The buttons of Nginx exercise and the first button behave differently but you want them to match.
# If you had to do any changes explain what you did and where.
# Submit the docker-compose.yml and both Dockerfiles.

version: '3.8'

services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - example-backend
      - example-frontend

  example-backend:
    image: example-backend
    ports:
      - 8080:8080
    environment:
      - FRONT_URL=http://localhost
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DATABASE=backend
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis

  example-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: example-frontend
    ports:
      - 5000:5000
    environment:
      - REQUEST_ORIGIN=http://localhost
      - API_URL=http://localhost/api

  redis:
    image: redis

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=backend

    volumes:
      - ./database:/var/lib/postgresql/data
