FROM golang:1.16-alpine

WORKDIR /app

RUN apk add --no-cache git && \
    git clone --depth 1 https://github.com/docker-hy/material-applications.git && \
    mv material-applications/example-backend/* . && \
    rm -rf material-applications

RUN go build

RUN addgroup -S app && adduser -S app -G app && chown app /app
USER app

EXPOSE 8080

ENV REQUEST_ORIGIN=http://localhost:5000

CMD ./server
