name: Build and Deploy to Azure Web App

on:
    push:
        branches:
            - main
        paths:
            - 'part-1/1-16/**'

env:
    IMAGE_NAME: isoteemu/devopswithdocker:1-16
    WEBAPP_NAME: 1-16

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Login into DockerHub
          uses: azure/docker-login@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: part-1/1-16
            file: part-1/1-16/Dockerfile
            push: true
            tags: $IMAGE_NAME


        - name: Deploy to Azure Web App
          uses: azure/webapps-deploy@v2
          with:
            app-name: ${{ env.WEBAPP_NAME }}
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            images: ${{ env.IMAGE_NAME }}
